# syntax=docker/dockerfile:1.19.0
ARG BASE_FROM
FROM ${BASE_FROM} AS gauss-base

ARG USERNAME=appuser
ARG USER_UID=1000
ARG USER_GID=$USER_UID
WORKDIR /home/${USERNAME}

RUN --mount=type=cache,target=/root/.cache/pip \
    source /opt/conda/etc/profile.d/conda.sh && \
    conda activate singularity && \
    CUDA_HOME='/usr/local/cuda' FORCE_CUDA="1" TORCH_CUDA_ARCH_LIST="8.6;8.7;8.9;9.0;10.0;12.0" pip install --no-warn-script-location --no-build-isolation \
        setuptools \
        plyfile \
        pytorch-lightning \
        imageio \
        ftfy \
        regex \
        git+https://github.com/openai/CLIP.git \
        altair \
        streamlit \
        protobuf \
        timm \
        tensorboard \
        tensorboardX \
        matplotlib \
        test-tube \
        wandb \
        torchmetrics \
        scikit-image \
        scikit-learn \
        torch-encoding \
        pycocotools \
        onnxruntime \ 
        onnx && \
    conda clean -afy

RUN --mount=type=cache,target=/root/.cache/pip \
    source /opt/conda/etc/profile.d/conda.sh && \
    conda activate singularity && \
    git clone --recursive https://github.com/ShijieZhou-UCLA/feature-3dgs.git /home/${USERNAME}/feature-3dgs && \
    cd /home/${USERNAME}/feature-3dgs && \
    sed -i '15i #include <cstdint>' submodules/diff-gaussian-rasterization-feature/cuda_rasterizer/rasterizer_impl.h && \
    sed -i 's/CUDA_ARCHITECTURES "[0-9;]*"/CUDA_ARCHITECTURES "86;87;89;90;100;120"/' submodules/diff-gaussian-rasterization-feature/CMakeLists.txt && \
    sed -i 's/^#define NUM_SEMANTIC_CHANNELS .*/#define NUM_SEMANTIC_CHANNELS 64 \/\/ Subject to change/' submodules/diff-gaussian-rasterization-feature/cuda_rasterizer/config.h && \
    TORCH_CUDA_ARCH_LIST="8.6;8.7;8.9;9.0;10.0;12.0" \
    CUDA_HOME=/usr/local/cuda \
    FORCE_CUDA=1 \
        pip install \
            submodules/diff-gaussian-rasterization-feature \
            submodules/simple-knn \
            encoders/sam_encoder \
            --no-warn-script-location \
            --no-build-isolation

RUN --mount=type=cache,target=/var/cache/apt \
    --mount=type=cache,target=/var/lib/apt/lists \
    apt-get -y update && apt-get -y install \
    libglew-dev \
    libassimp-dev \
    libboost-all-dev \
    libgtk-3-dev \
    libglfw3-dev \
    libavdevice-dev \
    libavcodec-dev \
    libeigen3-dev \
    libxxf86vm-dev \
    && \
    rm -rf /var/lib/apt/lists/*

RUN wget https://github.com/RenderKit/embree/releases/download/v3.13.5/embree-3.13.5.x86_64.linux.tar.gz -O /home/${USERNAME}/feature-3dgs/embree.tar.gz \
    && mkdir -p /home/${USERNAME}/feature-3dgs/embree \
    && tar -xzf /home/${USERNAME}/feature-3dgs/embree.tar.gz -C /home/${USERNAME}/feature-3dgs/embree \
    && rm -rf /home/${USERNAME}/feature-3dgs/embree.tar.gz

RUN git clone --recursive https://github.com/adam-ce/Gaussian-Splatting-Monitor.git /home/${USERNAME}/feature-3dgs/Gaussian-Splatting-Monitor \
    && cd /home/${USERNAME}/feature-3dgs/Gaussian-Splatting-Monitor/SIBR_viewers \
    && cmake -Bbuild . -DCMAKE_BUILD_TYPE=Release -Dembree_DIR:PATH=/home/${USERNAME}/feature-3dgs/embree/embree-3.13.5.x86_64.linux/lib/cmake/embree-3.13.5/ -G Ninja && \
    cmake --build build --target install -- -j"$(nproc)"

USER ${USERNAME}
WORKDIR /home/${USERNAME}

CMD ["/bin/bash"]
